name: CI
on:
  pull_request:
    branches: main
  push:
    branches: main
jobs:
  check-formatting-markdown:
    name: Check Formatting (Markdown)
    runs-on: ubuntu-latest
    container: ghcr.io/devpow112/markdownlint
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: Check formatting
        run: find . -type f -iname '*.md' -print0 | xargs -0 markdownlint
