name: CI
on:
  pull_request:
    branches: main
  push:
    branches: main
jobs:
  check-formatting-markdown:
    name: Check Formatting (Markdown)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Check formatting
        uses: actionshub/markdownlint@2.0.2
