name: CI
on:
  pull_request:
    branches: main
  push:
    branches: main
permissions:
  contents: read
jobs:
  check-formatting-markdown:
    name: Check Formatting (Markdown)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container: ghcr.io/devpow112/markdownlint
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Check formatting
        shell: bash
        run: find . -type f -iname '*.md' -print0 | xargs -0 markdownlint
