name: Update Statistics
on:
  push:
    branches: main
    paths: .github/workflows/update-statistics.yml
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:
permissions:
  contents: write
concurrency: update-statistics
jobs:
  update-statistics:
    name: Update Statistics
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      BASE_URL: https://github-readme-stats.vercel.app/api
      HIDE_BORDER: true
      THEME: github_dark
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false
      - name: Update statistics (overview)
        run: |
          URL="$BASE_URL?username=${{github.repository_owner}}"
          URL="$URL&hide_border=$HIDE_BORDER"
          URL="$URL&include_all_commits=true"
          URL="$URL&count_private=true"
          URL="$URL&line_height=20"
          URL="$URL&custom_title=Overview"
          URL="$URL&theme=$THEME"
          curl -sSfo images/statistics-overview.svg "$URL"
      - name: Update statistics (languages)
        run: |
          URL="$BASE_URL/top-langs?username=${{github.repository_owner}}"
          URL="$URL&hide_border=$HIDE_BORDER"
          URL="$URL&layout=compact"
          URL="$URL&langs_count=6"
          URL="$URL&theme=$THEME"
          curl -sSfo images/statistics-languages.svg "$URL"
      - name: Check for changes
        id: changes
        run: git diff --exit-code || echo '::set-output name=exist::true'
      - name: Push commit
        if: steps.changes.outputs.exist
        run: |
          git config user.name ${{secrets.AUTOMATION_USER}}
          git config user.email ${{secrets.AUTOMATION_EMAIL}}
          git add -u
          git commit -m "Update statistics"
          CREDENTIALS="x-access-token:$GITHUB_TOKEN"
          URL="https://$CREDENTIALS@github.com/${{github.repository}}.git"
          git remote set-url origin $URL
          git push origin main
        env:
          GITHUB_TOKEN: ${{secrets.AUTOMATION_TOKEN}}
